// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyQ-0FRs38DGAn8uHzWgBW3OsFheMZc8s',
    appId: '1:720552281748:web:a023b7d973dc7216f65681',
    messagingSenderId: '720552281748',
    projectId: 'test-project-dabac',
    authDomain: 'test-project-dabac.firebaseapp.com',
    storageBucket: 'test-project-dabac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxlifEzGlBXLahPwIJHFWDU9EW0Je49EA',
    appId: '1:720552281748:android:1cba01714887d8ecf65681',
    messagingSenderId: '720552281748',
    projectId: 'test-project-dabac',
    storageBucket: 'test-project-dabac.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyQ-0FRs38DGAn8uHzWgBW3OsFheMZc8s',
    appId: '1:720552281748:web:1e6aabe3be8613c2f65681',
    messagingSenderId: '720552281748',
    projectId: 'test-project-dabac',
    authDomain: 'test-project-dabac.firebaseapp.com',
    storageBucket: 'test-project-dabac.firebasestorage.app',
  );
}
